# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: ecommerceorder2
services:
  mongodb:
    image: mongo:8.0.4
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27018:27017
    # volumes:
    #   - ~/volumes/jhipster/ecommerceOrder2/mongodb/:/data/db/
    healthcheck:
      test: ['CMD', 'echo', '''db.runCommand("ping").ok''', '|', 'mongo', 'localhost:27017/test', '--quiet']
      interval: 5s
      timeout: 5s
      retries: 10
